name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Install pygame
        run: |
          pip install pygame

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run Pytest
        run: pytest  

      - name: Run Flake8
        run: flake8
        
